name: Add Reviewers

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      uses: madrapps/add-reviewers@v1
      with:
        github_token: ${{ secrets.TOKEN }}
        assignees: diegoslompo
